# DO NOT EDIT THIS FILE !!!!!!!!!!!!
#
# CONAS v3.0 output file
#
# Processor name: ARM 7
#
8 ; memory word width
#
32 ; address width
#
#
# Original file: Z:/home/tk/FER-stvari/arh1r/arm/pokazni_mi_2.a
#
#
<1,0>	                      ;; r1, r2, r3 - pokazivači na memorijske adrese ulaznih podataka
<2,0>	                      ;; r4, r5, r6 - podaci
<3,0>	                      ;; r7 - broj 0x8080
<4,0>	                      ;
<5,0>	                      ;
<6,0>	                      ;        org     0x200
<7,0>	00000200! 00 00 00 00 ;rez     dw      0
<8,0>	00000204! 80 80 00 00 ;zadnji  dw      0x8080
<9,0>	                      ;
<10,0>	                      ;
<11,0>	                      ;start
<12,0>	00000208  C0 1F A0 E3 ;        mov     r1, #0x300      ; inicijalizacija r1, r2, r3, i r7
<13,0>	0000020C  50 2E A0 E3 ;        mov     r2, #0x500
<14,0>	00000210  70 3E A0 E3 ;        mov     r3, #0x700
<15,0>	00000214  18 70 1F E5 ;        ldr     r7, 0x204
<16,0>	                      ;
<17,0>	                      ;petlja
<18,0>	00000218  B2 40 D1 E0 ;        ldrh    r4, [r1], #2    ; učitavanje podataka
<19,0>	0000021C  B2 50 D2 E0 ;        ldrh    r5, [r2], #2
<20,0>	00000220  B2 60 D3 E0 ;        ldrh    r6, [r3], #2
<21,0>	                      ;        
<22,0>	00000224  07 00 54 E1 ;        cmp     r4, r7          ; program se prekida kada je barem jedan od učitanih podataka jednak 0x8080
<23,0>	00000228  06 00 00 0A ;        beq     kraj
<24,0>	                      ;
<25,0>	0000022C  70 00 2D E9 ;        stmfd   sp!, {r4, r5, r6}       ; spremanje argumenata i pozivanje potprograma srednja
<26,0>	00000230  05 00 00 EB ;        bl      srednja
<27,0>	00000234  0C D0 8D E2 ;        add     sp, sp, #12
<28,0>	                      ;
<29,0>	00000238  40 00 1F E5 ;        ldr     r0, rez         ; učitavanje rezultata sa fiksne lokacije
<30,0>	                      ;
<31,0>	0000023C  70 1E 81 E2 ;        add     r1, r1, #0x700  ;upisivanje rezultata u memoriju
<32,0>	00000240  00 00 81 E5 ;        str     r0, [r1]
<33,0>	00000244  70 1E 41 E2 ;        sub     r1, r1, #0x700
<34,0>	                      ;
<35,0>	                      ;
<36,0>	                      ;kraj
<37,0>	00000248  56 34 12 EF ;        swi     0x123456
<38,0>	                      ;
<39,0>	                      ;
<40,0>	                      ;
<41,0>	                      ;srednja
<42,0>	0000024C  0E 40 2D E9 ;        stmfd   sp!, {r1, r2, r3, lr}
<43,0>	00000250  14 10 9D E5 ;        ldr     r1, [sp, #20]
<44,0>	00000254  18 20 9D E5 ;        ldr     r2, [sp, #24]
<45,0>	00000258  1C 30 9D E5 ;        ldr     r3, [sp, #28]
<46,0>	                      ;
#
# Debug Data
#
.debug:

#
#
# Assembling: OK