# DO NOT EDIT THIS FILE !!!!!!!!!!!!
#
# CONAS v3.0 output file
#
# Processor name: ARM 7
#
8 ; memory word width
#
32 ; address width
#
#
# Original file: Z:/home/tk/FER-stvari/arh1r/arm/test.a
#
#
<1,0>	                      ;main
<2,0>	                      ;
<3,0>	00000000  00 10 A0 E3 ;        mov     r1, #0
<4,0>	00000004  40 2F A0 E3 ;        mov     r2, #stvar
<5,0>	                      ;
<6,0>	00000008  01 10 81 E2 ;loop    add     r1, r1, #1
<7,0>	0000000C  00 10 82 E5 ;        str     r1, [r2]
<8,0>	00000010  08 50 A0 E3 ;        mov     r5, #loop
<9,0>	00000014  05 F0 A0 E1 ;        mov     pc, r5
<10,0>	                      ;
<11,0>	                      ;
<12,0>	                      ;end
<13,0>	00000018  56 34 12 EF ;        swi     0x123456
<14,0>	                      ;
<15,0>	                      ;
<16,0>	                      ;
<17,0>	                      ;        org     0x100
<18,0>	00000100! 00 00 00 00 ;stvar   dw      0
#
# Debug Data
#
.debug:
<6,0> <7,0> <9,0> <!h18,0> 
#
#
# Assembling: OK