# DO NOT EDIT THIS FILE !!!!!!!!!!!!
#
# CONAS v3.0 output file
#
# Processor name: RV32I
#
8 ; memory word width
#
32 ; address width
#
#
# Original file: Z:/home/tk/FER-stvari/arh1r/frisc-v/lab3++.a
#
#
<1,0>	                      ;
#
# Debug Data
#
.debug:

#
#
# Assembling: OK