# DO NOT EDIT THIS FILE !!!!!!!!!!!!
#
# CONAS v3.0 output file
#
# Processor name: RV32I
#
8 ; memory word width
#
32 ; address width
#
#
# Original file: Z:/home/tk/FER-stvari/arh1r/frisc-v/test_04_function.a
#
#
<1,0>	                      ;; Poziv funkcije koja registrom x12 vraća razliku većeg i manjeg broja te 
<2,0>	                      ;; spremanje rezultata na adresu 0x100
<3,0>	                      ;; Funkcija parametre prima registrima x10 i x11
<4,0>	                      ;; Točan rezultat je 0x02 za trenutni setup
<5,0>	                      ;;-----------------------------------------------------------------------------------------
<6,0>	                      ;        org 0
<7,0>	                      ;
<8,0>	00000000  13 05 50 00 ;glavni  addi x10, x0, 5         ; stavi broj 5 u registar x10
<9,0>	00000004  93 05 30 00 ;        addi x11, x0, 3         ; stavi broj 3 u registar x11
<10,0>	                      ;
<11,0>	00000008  EF 00 C0 00 ;        jal ra, oduzmi          ; pozovi potprogram
<12,0>	0000000C  23 20 C0 10 ;        sw x12, 0x100(x0)       ; spremi rezultat na adresu 0x100
<13,0>	                      ;
<14,0>	00000010  6F F0 10 7F ;        halt                    ; kraj
<15,0>	                      ;;-----------------------------------------------------------------------------------------
<16,0>	                      ;; potprogram za računanje razlike većeg i manjeg broja
<17,0>	                      ;;-----------------------------------------------------------------------------------------
<18,0>	00000014  63 56 B5 00 ;oduzmi  bge x10, x11, veci1     ; ako je x10 > x11 treba izračunati x10 - x11,
<19,0>	                      ;                                ; ako ne x11 - x10
<20,0>	                      ;
<21,0>	00000018  33 86 A5 40 ;veci2   sub x12, x11, x10       ; x11 - x10
<22,0>	0000001C  63 04 00 00 ;        beq x0, x0, nazad       ; skok na povratak
<23,0>	                      ;
<24,0>	00000020  33 06 B5 40 ;veci1   sub x12, x10, x11       ; x10 - x11
<25,0>	                      ;
<26,0>	00000024  67 80 00 00 ;nazad   jalr x0, 0(ra)          ; povratak u glavni program
<27,0>	                      ;;-----------------------------------------------------------------------------------------
#
# Debug Data
#
.debug:

#
#
# Assembling: OK